openapi: 3.1.0

info:
  title: Interview Agent Content API
  description: |
    Dynamic content loader for Interview Agent. Fetches configurations, question banks,
    tasks, and templates from GitHub repository using index-based navigation.

    Start with index files for each category, then load specific resources as needed.
  version: 3.0.0
  contact:
    name: Interview Agent
    url: https://github.com/bardin08/interview-agent

servers:
  - url: https://raw.githubusercontent.com/Bardin08/interview-agent/refs/heads/main/

paths:
  /config/{filepath}:
    get:
      operationId: getConfigResource
      summary: Load configuration file
      description: Load config files. Start with index.yaml to discover available configs, then load specific files. Supports nested paths.
      security:
        - githubToken: []
        - {}
      parameters:
        - name: filepath
          in: path
          required: true
          description: File path relative to config directory
          schema:
            type: string
          example: index.yaml
      responses:
        '200':
          description: Configuration file content in YAML format
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Resource not found

  /technologies/{filepath}:
    get:
      operationId: getTechnologiesResource
      summary: Load technology resource
      description: Load tech resources. Start with index.yaml for registry, then load tech-specific configs, questions, or competency matrices.
      security:
        - githubToken: []
        - {}
      parameters:
        - name: filepath
          in: path
          required: true
          description: File path relative to technologies directory
          schema:
            type: string
          example: index.yaml
      responses:
        '200':
          description: Technology resource content (YAML or Markdown)
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Resource not found

  /tasks/{filepath}:
    get:
      operationId: getTasksResource
      summary: Load task file
      description: Load task workflow files. Start with index.yaml to discover available tasks, then load specific task definitions.
      security:
        - githubToken: []
        - {}
      parameters:
        - name: filepath
          in: path
          required: true
          description: File path relative to tasks directory
          schema:
            type: string
          example: index.yaml
      responses:
        '200':
          description: Task file content in Markdown format
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Resource not found

  /templates/{filepath}:
    get:
      operationId: getTemplatesResource
      summary: Load template file
      description: Load template files. Start with index.yaml to discover available templates, then load specific report or session templates.
      security:
        - githubToken: []
        - {}
      parameters:
        - name: filepath
          in: path
          required: true
          description: File path relative to templates directory
          schema:
            type: string
          example: index.yaml
      responses:
        '200':
          description: Template file content (YAML or Markdown)
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Resource not found

components:
  schemas: {}

  securitySchemes:
    githubToken:
      type: apiKey
      in: header
      name: Authorization
      description: |
        GitHub Personal Access Token for higher rate limits.
        Format: "Bearer YOUR_GITHUB_TOKEN"

        Without token: 60 requests/hour
        With token: 5,000 requests/hour

security:
  - githubToken: []
  - {}

externalDocs:
  description: Interview Agent Documentation
  url: https://github.com/bardin08/interview-agent
