openapi: 3.1.0

info:
  title: Interview Agent Content API
  description: |
    Dynamic content loader for Interview Agent. Fetches configurations, question banks,
    tasks, and templates from GitHub repository using index-based navigation.

    Start with index files for each category, then load specific resources as needed.
  version: 3.0.0
  contact:
    name: Interview Agent
    url: https://github.com/bardin08/interview-agent

servers:
  - url: https://raw.githubusercontent.com/Bardin08/interview-agent/refs/heads/main/

paths:
  /config/{filepath}:
    get:
      operationId: getConfigResource
      summary: Load agent configuration files
      description: "Step 1: Call with filepath='index.yaml'. Step 2: Use file names from response (e.g., filepath='core-principles.yaml'). DO NOT prefix with 'config/'."
      security:
        - githubToken: []
        - {}
      parameters:
        - name: filepath
          in: path
          required: true
          description: "Relative path only. Examples: 'index.yaml', 'core-principles.yaml', 'interview-framework/hint-system.yaml'. Never: 'config/index.yaml'"
          schema:
            type: string
          examples:
            index:
              value: "index.yaml"
              summary: First call to list all configs
            root_file:
              value: "core-principles.yaml"
              summary: Load file from config root
            nested_file:
              value: "interview-framework/hint-system.yaml"
              summary: Load file from subdirectory
      responses:
        '200':
          description: Configuration file content in YAML format
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Resource not found

  /technologies/{filepath}:
    get:
      operationId: getTechnologiesResource
      summary: Load technology resources
      description: "Step 1: filepath='index.yaml' for navigation. Step 2: filepath='supported-technologies.yaml' for tech registry. Step 3: filepath='csharp/config.yaml' for specific resources."
      security:
        - githubToken: []
        - {}
      parameters:
        - name: filepath
          in: path
          required: true
          description: "Relative path only. Examples: 'index.yaml', 'supported-technologies.yaml', 'csharp/config.yaml'. Never: 'technologies/...'"
          schema:
            type: string
          examples:
            index:
              value: "index.yaml"
              summary: First call - navigation index
            registry:
              value: "supported-technologies.yaml"
              summary: Second call - technology registry with IDs
            tech_config:
              value: "csharp/config.yaml"
              summary: Load C# technology config
            tech_questions:
              value: "csharp/questions.md"
              summary: Load C# questions bank
            tech_matrix:
              value: "csharp/competency-matrix.yaml"
              summary: Load C# competency matrix
      responses:
        '200':
          description: Technology resource content (YAML or Markdown)
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Resource not found

  /tasks/{filepath}:
    get:
      operationId: getTasksResource
      summary: Load task workflow files
      description: "Step 1: Call with filepath='index.yaml'. Step 2: Use file names from response (e.g., filepath='conduct-interview.md'). DO NOT prefix with 'tasks/'."
      security:
        - githubToken: []
        - {}
      parameters:
        - name: filepath
          in: path
          required: true
          description: "Relative path only. Examples: 'index.yaml', 'conduct-interview.md'. Never: 'tasks/conduct-interview.md'"
          schema:
            type: string
          examples:
            index:
              value: "index.yaml"
              summary: First call to list all tasks
            task_file:
              value: "conduct-interview.md"
              summary: Load specific task workflow
      responses:
        '200':
          description: Task file content in Markdown format
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Resource not found

  /templates/{filepath}:
    get:
      operationId: getTemplatesResource
      summary: Load template files
      description: "Step 1: Call with filepath='index.yaml'. Step 2: Use file names from response (e.g., filepath='interview-report-tmpl.md'). DO NOT prefix with 'templates/'."
      security:
        - githubToken: []
        - {}
      parameters:
        - name: filepath
          in: path
          required: true
          description: "Relative path only. Examples: 'index.yaml', 'interview-report-tmpl.md'. Never: 'templates/interview-report-tmpl.md'"
          schema:
            type: string
          examples:
            index:
              value: "index.yaml"
              summary: First call to list all templates
            template_file:
              value: "interview-report-tmpl.md"
              summary: Load specific template
      responses:
        '200':
          description: Template file content (YAML or Markdown)
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Resource not found

components:
  schemas: {}

  securitySchemes:
    githubToken:
      type: apiKey
      in: header
      name: Authorization
      description: |
        GitHub Personal Access Token for higher rate limits.
        Format: "Bearer YOUR_GITHUB_TOKEN"

        Without token: 60 requests/hour
        With token: 5,000 requests/hour

security:
  - githubToken: []
  - {}

externalDocs:
  description: Interview Agent Documentation
  url: https://github.com/bardin08/interview-agent
